# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 05:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='RegStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField()),
                ('storeslug', models.CharField(max_length=120, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('DEL', 'Delhi'), ('MUM', 'Mumbai')], default='DEL', max_length=3)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Wrong Mobile Number ', regex='^(\\+91[\\-\\s]?)?[89]\\d{9}$')])),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.Category')),
            ],
        ),
    ]
