# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 05:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=70)),
                ('point', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326)),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.RegStore')),
            ],
        ),
    ]
