# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='regstore',
            name='main_pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
