# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_regstore_main_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='regstore',
            name='owner',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regstore',
            name='main_pic',
            field=models.ImageField(upload_to='/static/store_img/'),
        ),
    ]
