# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.RegStore'),
            preserve_default=False,
        ),
    ]
