# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_comments_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ratings',
            field=models.IntegerField(choices=[(1, '0.5'), (2, '1'), (3, '1.5'), (4, '2'), (5, '2.5'), (6, '3'), (7, '3.5'), (8, '4'), (9, '4.5'), (10, '5')]),
        ),
    ]
