# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_comments_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 18, 17, 59, 46, 539711, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
