# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20160426_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regstore',
            name='city',
            field=models.CharField(choices=[('delhi', 'Delhi'), ('mumbai', 'Mumbai')], default='delhi', max_length=20),
        ),
    ]
