# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20160502_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='neg_score_comment',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='polarity_comment',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='pos_score_comment',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
