# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20160503_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
