# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0014_auto_20160426_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_score', models.IntegerField()),
                ('neg_score', models.IntegerField()),
                ('polarity', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.RegStore')),
            ],
        ),
    ]
