# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senticomment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='neg_score',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='review',
            name='polarity',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='review',
            name='pos_score',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
