# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senticomment', '0003_auto_20160501_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.RegStore'),
        ),
    ]
