# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('senticomment', '0004_auto_20160502_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 2, 7, 26, 20, 615299, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.RegStore', unique_for_date=models.DateTimeField(auto_now_add=True)),
        ),
    ]
