# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senticomment', '0005_auto_20160502_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='no_of_comments',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
