# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senticomment', '0006_review_no_of_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.RegStore', unique_for_date=models.DateTimeField()),
        ),
    ]
