# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20160502_1634'),
        ('senticomment', '0008_auto_20160502_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_score_comment', models.DecimalField(decimal_places=4, max_digits=6)),
                ('neg_score_comment', models.DecimalField(decimal_places=4, max_digits=6)),
                ('polarity_comment', models.DecimalField(decimal_places=4, max_digits=6)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Comments')),
            ],
        ),
    ]
