# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senticomment', '0009_reviewcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcomment',
            name='comment',
        ),
        migrations.DeleteModel(
            name='ReviewComment',
        ),
    ]
