# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20160216_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegForm',
            new_name='RegUser',
        ),
        migrations.DeleteModel(
            name='LoginForm',
        ),
    ]
