# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_auto_20160219_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
