# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_auto_20160220_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegUser',
        ),
    ]
