# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0007_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='fir',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='las',
        ),
    ]
