# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0008_auto_20160401_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
